title: Study of exemplarism
questions:
    - text: what is the question the article is asking?
      coding:
        - criteria: Q1-1
          min: 0
          max: 1
        - criteria: Q1-2
          min: 0
          max: 5
        - criteria: Q1-3
          min: 0
          max: 10
        - criteria: Q1-4
          min: 0
          max: 1
    - text: "how was the question asked "
      coding:
        - criteria: Q2-1
          min: 0
          max: 1
        - criteria: Q2-2
          min: 0
          max: 5
        - criteria: Q2-3
          min: 0
          max: 10
        - criteria: Q2-4
          min: 0
          max: 1
    - text: why is the finding important
      coding:
        - criteria: Q3-1
          min: 0
          max: 1
        - criteria: Q3-2
          min: 0
          max: 5
        - criteria: Q3-3
          min: 0
          max: 10
        - criteria: Q3-4
          min: 0
          max: 1
    - text: And what was the answer
      coding:
        - criteria: Q4-1
          min: 0
          max: 1
        - criteria: Q4-2
          min: 0
          max: 5
        - criteria: Q4-3
          min: 0
          max: 10
        - criteria: Q4-4
          min: 0
          max: 1
    - text: what are some possible weaknesses of the study
      coding:
        - criteria: Q5-1
          min: 0
          max: 1
        - criteria: Q5-2
          min: 0
          max: 5
        - criteria: Q5-3
          min: 0
          max: 10
        - criteria: Q5-4
          min: 0
          max: 1
show:
    - group
order: random
user: MGM
